### ISSUE TITLE
Singular solve segfaults for univariate polynomials

### ISSUE THREAD

**Issue by saschatimme** [oscar-system/Singular.jl#187]
Using Julia 1.2 I get this:

```julia
julia> R, (s,) = PolynomialRing(Singular.QQ, ["s"])
(Singular Polynomial Ring (QQ),(s),(dp(1),C), spoly{n_Q}[s])

julia> 

julia> Singular.Ideal(R, [s^33-3*s^32-6*s^31-s^30+3*s^23-s^15])
Singular Ideal over Singular Polynomial Ring (QQ),(s),(dp(1),C) with generators (s^33-3*s^32-6*s^31-s^30+3*s^23-s^15)

julia> I = Singular.Ideal(R, [s^33-3*s^32-6*s^31-s^30+3*s^23-s^15])
Singular Ideal over Singular Polynomial Ring (QQ),(s),(dp(1),C) with generators (s^33-3*s^32-6*s^31-s^30+3*s^23-s^15)

julia> Singular.LibSolve.
fglm_solve     laguerre_solve  mp_res_mat      solve           triangLf_solve  triang_solve
interpolate    lex_solve       simplexOut      triangL_solve   triangM_solve   ures_solve
julia> Singular.LibSolve.solve(I)
// ** loaded /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/bin/../share/singular/LIB/solve.lib (4.1.2.0,Feb_2019)
// ** loaded /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/bin/../share/singular/LIB/ring.lib (4.1.2.0,Feb_2019)
// ** loaded /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/bin/../share/singular/LIB/primdec.lib (4.1.2.0,Feb_2019)
// ** loaded /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/bin/../share/singular/LIB/absfact.lib (4.1.2.0,Feb_2019)
// ** loaded /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/bin/../share/singular/LIB/matrix.lib (4.1.2.0,Feb_2019)
// ** loaded /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/bin/../share/singular/LIB/nctools.lib (4.1.2.0,Feb_2019)
// ** loaded /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/bin/../share/singular/LIB/random.lib (4.1.2.0,Feb_2019)
// ** loaded /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/bin/../share/singular/LIB/poly.lib (4.1.2.0,Feb_2019)
// ** loaded /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/bin/../share/singular/LIB/elim.lib (4.1.2.0,Feb_2019)
// ** loaded /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/bin/../share/singular/LIB/general.lib (4.1.2.0,Feb_2019)
// ** loaded /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/bin/../share/singular/LIB/inout.lib (4.1.2.0,Feb_2019)
// ** loaded /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/bin/../share/singular/LIB/triang.lib (4.1.2.0,Feb_2019)
[1]:
-0.89521895
[2]:
4.4114706
[3]:
(-1.1482541+i*0.17026655)
[4]:
(-1.1482541-i*0.17026655)
[5]:
(-0.66557296+i*0.58989253)
[6]:
(-0.66557296-i*0.58989253)
[7]:
(-0.56567524+i*0.74847289)
[8]:
(-0.56567524-i*0.74847289)
[9]:
(-0.090798442+i*0.87424398)
[10]:
(-0.090798442-i*0.87424398)
[11]:
(0.11962281+i*0.88093791)
[12]:
(0.11962281-i*0.88093791)
[13]:
(0.53509334+i*0.68993065)
[14]:
(0.53509334-i*0.68993065)
[15]:
(0.69319204+i*0.53157745)
[16]:
(0.69319204-i*0.53157745)
[17]:
(0.86426672-i*0.11380014)
[18]:
(0.86426672+i*0.11380014)
[19]:
0

// 'solve' created a ring, in which a list SOL of numbers (the complex solutions)
// is stored.
// To access the list of complex solutions, type (if the name R was assigned
// to the return value):
        setring R; SOL; 
2-element Array{Any,1}:

signal (11): Segmentation fault: 11
in expression starting at REPL[11]:0
__gmpz_sizeinbase at /Applications/Julia-1.3.app/Contents/Resources/julia/lib/julia/libgmp.10.dylib (unknown line)
_Z7nlWriteP7snumberP9n_Procs_s at /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/lib/libpolys-4.1.2.dylib (unknown line)
_ZZ22singular_define_coeffsRN5jlcxx6ModuleEENK4$_11clEP7snumberP9n_Procs_si at /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/lib/libsingularwrap.dylib (unknown line)
_ZNSt3__1L8__invokeIRZ22singular_define_coeffsRN5jlcxx6ModuleEE4$_11JP7snumberP9n_Procs_siEEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOSA_DpOSB_ at /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/lib/libsingularwrap.dylib (unknown line)
_ZNSt3__128__invoke_void_return_wrapperIvE6__callIJRZ22singular_define_coeffsRN5jlcxx6ModuleEE4$_11P7snumberP9n_Procs_siEEEvDpOT_ at /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/lib/libsingularwrap.dylib (unknown line)
_ZNSt3__110__function12__alloc_funcIZ22singular_define_coeffsRN5jlcxx6ModuleEE4$_11NS_9allocatorIS5_EEFvP7snumberP9n_Procs_siEEclEOS9_OSB_Oi at /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/lib/libsingularwrap.dylib (unknown line)
_ZNSt3__110__function6__funcIZ22singular_define_coeffsRN5jlcxx6ModuleEE4$_11NS_9allocatorIS5_EEFvP7snumberP9n_Procs_siEEclEOS9_OSB_Oi at /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/lib/libsingularwrap.dylib (unknown line)
_ZNKSt3__110__function12__value_funcIFvP7snumberP9n_Procs_siEEclEOS3_OS5_Oi at /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/lib/libsingularwrap.dylib (unknown line)
_ZNKSt3__18functionIFvP7snumberP9n_Procs_siEEclES2_S4_i at /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/lib/libsingularwrap.dylib (unknown line)
_ZN5jlcxx6detail17ReturnTypeAdapterIvJP7snumberP9n_Procs_siEEclEPKvNS_13WrappedCppPtrES9_i at /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/lib/libsingularwrap.dylib (unknown line)
_ZN5jlcxx6detail11CallFunctorIvJP7snumberP9n_Procs_siEE5applyEPKvNS_13WrappedCppPtrES9_i at /Users/sascha/.julia/packages/Singular/7PalX/deps/usr/lib/libsingularwrap.dylib (unknown line)
n_Write_internal at ./none:0 [inlined]
n_Write at /Users/sascha/.julia/packages/Singular/7PalX/src/libsingular/coeffs.jl:18
unknown function (ip: 0x12b2ece96)
show at /Users/sascha/.julia/packages/Singular/7PalX/src/number/n_Q.jl:108
show_delim_array at ./show.jl:665
show_delim_array at ./show.jl:654 [inlined]
show_vector at ./arrayshow.jl:443
show_vector at ./arrayshow.jl:432 [inlined]
show at ./arrayshow.jl:418
show at ./show.jl:604
show at ./dict.jl:38
#sprint#339 at ./strings/io.jl:103
unknown function (ip: 0x12b2ea3f2)
#sprint at ./none:0 [inlined]
alignment at ./show.jl:1801
unknown function (ip: 0x12b2ea160)
alignment at ./arrayshow.jl:68
unknown function (ip: 0x12b2e9a94)
print_matrix at ./arrayshow.jl:186
print_matrix at ./arrayshow.jl:159 [inlined]
print_array at ./arrayshow.jl:308 [inlined]
show at ./arrayshow.jl:345
display at /Users/sascha/.julia/packages/OhMyREPL/z9Xlq/src/output_prompt_overwrite.jl:6
display at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:136
display at ./multimedia.jl:323
jl_apply at /Users/sabae/buildbot/worker/package_macos64/build/src/./julia.h:1631 [inlined]
jl_f__apply at /Users/sabae/buildbot/worker/package_macos64/build/src/builtins.c:627
jl_f__apply_latest at /Users/sabae/buildbot/worker/package_macos64/build/src/builtins.c:665
#invokelatest#1 at ./essentials.jl:709 [inlined]
invokelatest at ./essentials.jl:708 [inlined]
print_response at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:156
print_response at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:141
jfptr_print_response_14159.clone_1 at /Applications/Julia-1.3.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
do_respond at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:719
unknown function (ip: 0x12b2b91d3)
jl_apply at /Users/sabae/buildbot/worker/package_macos64/build/src/./julia.h:1631 [inlined]
jl_f__apply at /Users/sabae/buildbot/worker/package_macos64/build/src/builtins.c:627
jl_f__apply_latest at /Users/sabae/buildbot/worker/package_macos64/build/src/builtins.c:665
#invokelatest#1 at ./essentials.jl:709 [inlined]
invokelatest at ./essentials.jl:708 [inlined]
run_interface at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/REPL/src/LineEdit.jl:2306
run_frontend at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:1045
run_repl at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:201
#770 at ./client.jl:382
jfptr_#770_7602.clone_1 at /Applications/Julia-1.3.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/sabae/buildbot/worker/package_macos64/build/src/./julia.h:1631 [inlined]
jl_f__apply at /Users/sabae/buildbot/worker/package_macos64/build/src/builtins.c:627
jl_f__apply_latest at /Users/sabae/buildbot/worker/package_macos64/build/src/builtins.c:665
#invokelatest#1 at ./essentials.jl:709 [inlined]
invokelatest at ./essentials.jl:708 [inlined]
run_main_repl at ./client.jl:366
exec_options at ./client.jl:304
_start at ./client.jl:460
jfptr__start_2084.clone_1 at /Applications/Julia-1.3.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
true_main at /usr/local/bin/julia (unknown line)
main at /usr/local/bin/julia (unknown line)
Allocations: 33281390 (Pool: 33273279; Big: 8111); GC: 36
zsh: segmentation fault  julia --project=.
```

**Comment by wbhart** [comment]
The segfault seems to happen in Singular itself, so I will pass this to @hannes14 for now. Of course the problem can still be that we are doing something stupid in Singular.jl, so he may end up passing this back to me.

Thanks for the report.

**Comment by hannes14** [comment]
The problem is in the change of the used ring during the function "solve": input is in QQ[s], output in (complex(i))[s], but the printing routine for QQ was used on the complex floating point numbers.
In Singular this cannot happen: one has to change the ring (manually) before one can access the solutions. In Singular.jl the correct ring must be set (as the parent object).
Usually the converting routines in Singular.jl sets the parent to the same rings as the arguments had.

**Comment by wbhart** [comment]
Yeah this is probably due to the fact that everything in Singular.jl that calls the Singular interpreter just goes through Sebastian's generic code for this. It doesn't know that the output has to have a different type and so it never sets the parent of the return values correctly, and it certainly can't have a clue what to set it to.

Now if only someone could have predicted that this sort of thing would happen.....

**Comment by wbhart** [comment]
Incidentally, I have *absolutely no idea* how to fix this!

**Comment by wbhart** [comment]
So @tthsqe12 and I looked through the Singular.jl code that handles Singular library calls, and it seems that the original code above was incorrect.

It should not have been Singular.LibSolve.solve(I) but Singular.LibSolve.solve(C, I) where C is the ring you want the output to be in. In other words, you need to create the output ring first, and pass it to the function. This is in fact the only way it could work, even in theory. It's impossible once the Singular ring is created internally for us to determine what it is. So we can't construct it on the Julia side. And even if we could construct it, we would have no way to determine if it is the same as another ring already constructed, or what the reference count should be etc.

Now, the minor problem at the moment is there is no way for you to create the ring complex(i) in Singular.jl at present. So someone will have to implement that before this example will work.

**Comment by wbhart** [comment]
By the way, here is the beautiful, mathematically correct heuristic it uses to try and compute the correct ring for the output if it isn't supplied:

* for each input argument d
   - if the ring of d is not nothing, then return d

**Comment by wbhart** [comment]
On the other hand, it is of course impossible for you to create the same ring that Singular is going to create for you, even if you know what it should mathematically be. So how this can ever work, I don't know. Probably it never will.

**Comment by tthsqe12** [comment]
As far as I can tell, the function `low_level_caller` in `caller.jl` has to infer a currRing for the call to singular. While the inference of this ring (`rng`) could be improved, it is also seemingly used to convert the output on https://github.com/oscar-system/Singular.jl/blob/master/src/caller.jl#L188.

I would say this is why Singular.jl thinks the output is in QQ when it is not.

**Comment by fingolfin** [comment]
I just discovered this issue. Let me start by pointing out that all the work Sebastian did there was based on the GAP-Singular interface [SingularInterface](https://github.com/gap-packages/SingularInterface) which we developed in close partnership with @hannes14. To be precise, I explained to Sebastian how it works roughly and he then set out to wrote his code (and I still think that was an important and crucial step). Alas, his code was a prototype and not complete (this is not meant as a slight! Rather it is no surprise given the timeframe he wrote it in -- he simply left before he could complete it). It's also not unsurprising that he missed some of the finer points of the design in SingularInterface.

For example, the mentioned ring heuristic in SingularInterface is quite a lot more complex (and some of that complexity could perhaps go these days; but let me emphasise that it was developed in coordination with @hannes14, not just dreamed up on the spot).

Let me point out one crucial bit of infrastructure that seems to be missing from Singular.jl: for the GAP-Singular interface, @hannes14 added the field `ext_ref` to Singular rings. In there, we stored a pointer to the GAP wrapper for that ring. That way, it was trivial to enforce that every Singular ring had at most one wrapper object. Due to ref counting, the ring could never be freed before the GAP wrapper was garbage collected. A finalization method for the wrapper objects was added to ensure the Singular ring ref counter was eventually decremented. (Note that the finalizer must not do this immediately, as in a single GC sweep phase, multiple objects can be finalized, including e.g. elements of that ring; so instead, the finalizer pushes the Singular ring into a cleanup queue, which is then processed in a post-gc hook).

There is then a helper function like `wrapper(SingularRing)` which takes a C pointer to a Singular ring (or qring) and does  `if (!r->ext_ring) { r->ext_ring = NewJuliaWrapp(r) } return r->ext_ring;`


I just deleted a lengthy explanation of how the heuristic in SingularInterface works, because I think it's actually irrelevant for this case: the  problem seems to be (as far as I understand the output posted in the original issue) that the return value is a new ring, and that this is not dealt with. This is simply missing code, plus a lack of use of `ext_ref`. I think if `Singular.jl` started to populate `ext_ref` as outlined above, with some modest effort we could fix this issue here and more. Looking at the SingularInterface might also help; feel free to ask me about it. 

(Perhaps one could even compel me to actively contribute to this, but I have a TON of other things on my plate, so I am kinda hoping other people will step up here)

**Comment by tthsqe12** [comment]
I will start working on this.

**Comment by tthsqe12** [comment]
As far as I can tell the offending line is
https://github.com/oscar-system/Singular.jl/blob/master/src/caller.jl#L62
which calls the following nonsensical function in PolyTypes.jl
```
function (R::PolyRing{T})(r::libSingular.ring_ptr) where T
    new_r = deepcopy(R)
    new_ptr = new_r.ptr
    new_r.ptr = r
    return new_r
end
```
There are only a very limited set of circumstances in which this function could possibly be correct.

@hannes14 We need to be able to populate the members of the PolyRing struct
```
mutable struct PolyRing{T <: Nemo.RingElem} <: Nemo.MPolyRing{T}
   ptr::libSingular.ring_ptr
   base_ring::Union{Ring, Field}
   ord::Symbol
   refcount::Int
```
given only the first one. That is, given a `libSingular.ring_ptr` we need to get the coefficient `Ring` or `Field` and the ordering if it is one of the supported orderings.

**Comment by thofma** [comment]
This is still an issue. @hannes14, can we try what @tthsqe12 proposed?

**Comment by hannes14** [comment]
Fine with me:
to find the coefficient ring/field: use nCoeff_is_.. routines or use r->cf->type (which is of type n_coeffType, has n_Zp,n_Q, etc)
to find the ordering, check r->order.

**Comment by fingolfin** [comment]
@tthsqe12 is this still something you are looking into?

**Comment by tthsqe12** [comment]
It is on my todo list. However, it is a deep issue I think, and I am not sure what the best way to solve it is.
