### ISSUE TITLE
How to convert a matrix into a module?

### ISSUE THREAD

**Issue by mohamed-barakat** [oscar-system/Singular.jl#316]
In Singular several commands accepts either modules or matrices as input. In fact, modules, are a sort of column-oriented sparse matrix data structure. Now that I want to use the "Groebner basics" `std`, `syz`, `lift`, `lift_std`, `modulo` located in `src/module/module.jl` the input must be a module (i.e., type `smodule`).

1. Is there a way to install such methods for matrices? and/or
2. Is it possible to install a method `Module` which takes a matrix as input and converts it to the type `smodule`?

**Comment by wbhart** [comment]
I'm not sure 1 makes mathematical sense. But I believe the Singular library has a way to do 2, so that should be possible.

**Comment by mohamed-barakat** [comment]
I would even argue that a GB needs explicit submodule generators as input. This data structure is called a matrix (either column- or row-oriented) ;)

**Comment by wbhart** [comment]
@fieker has opinions on that. I believe this would be a list of generators, rather than a matrix, but yeah, something like that.

**Comment by mohamed-barakat** [comment]
The GB algorithm over multivariate polynomial rings (k[x,y,...]) specializes to the Gaussian NF (over field k) and the Hermite NF (over a univariate polynomial ring k[x]). And in these two special cases, one usually uses the matrix and not the module language. One only needs to distinguish if the action is on rows (REF) or on columns (CEF). Singular chose the variant which acts on columns, while GB with tail reduction specializes to CREF (= column reduced echelon form).

```
$ Singular
                     SINGULAR                                 /  Development
 A Computer Algebra System for Polynomial Computations       /   version 4.1.3
                                                           0<
 by: W. Decker, G.-M. Greuel, G. Pfister, H. Schoenemann     \   Mar 2020
FB Mathematik der Universitaet, D-67653 Kaiserslautern        \
> ring r=0,dummy,(dp,c);
> matrix m[3][2]=1,2,3,4,5,6;
> print(m);
1,2,
3,4,
5,6
> print(matrix(std(m)));
0,1,
1,2,
2,3
> option(redSB);
> print(matrix(std(m)));
0,1,
1,0,
2,-1
```

**Comment by mohamed-barakat** [comment]
As one can see here, there are reasons (in fact many) why one would need to convert `smodule` into a matrix

https://oscar-system.github.io/Singular.jl/latest/module/#Free-resolutions-1

implying that the converse is also true.

**Comment by wbhart** [comment]
We certainly have one direction already.

As for the "mathematical sense" thing, I just mean that a matrix is not mathematically defined to be a set of submodule generators. Of course the latter can be thought of as the former and one can represent the latter using the former as a data structure (and there are good reasons to do so). But regardless of what the internal representation is, the question is how will the user of a computer algebra system want a set of generators to be represented? The answer in my opinion is as a list (in fact a Vector) of objects, each of which is a submodule generator which can be passed to functions which accept submodule generators.

This is something @fieker and I discussed when I did the submodules in AbstractAlgebra.jl [1]. Of course internally there is nothing stopping you storing this as a matrix (and quite possibly we do). And for ease of use, one even wants a function to return the matrix representation of this data. (According to the documentation we did not do this, though I thought someone added some such functionality recently. Perhaps that didn't make it to the docs yet.)

But I suspect you were talking about something internal, rather than the way things are presented to the user, and so there what you said of course makes sense. (It's worth bearing in mind that in AbstractAlgebra the internal representation is not as trivial and that we don't necessarily follow the same convention as Singular here.)

[1] https://nemocas.github.io/AbstractAlgebra.jl/latest/submodule/
