### ISSUE TITLE
Iterate over ideals

### ISSUE THREAD

**Issue by wbhart** [oscar-system/Singular.jl#492]
It would be nice to be able to iterate over the generators of an ideal:

```
I = Ideal(R, x, y)
for v in I
   # blah
end
```

**Comment by fieker** [comment]
On Fri, Sep 10, 2021 at 04:10:04AM -0700, wbhart wrote:
> It would be nice to be able to iterate over the generators of an ideal:
> 
> ```
> I = Ideal(R, x, y)
> for v in I
>    # blah
> end
> ```

This should iterate over all elements of the ideal...
for v in gens(I) ?

**Comment by wbhart** [comment]
What should that mean? Aren't there infinitely many elements? How would I order them? It doesn't seem like a useful operation.

**Comment by tthsqe12** [comment]
I would say for consistency  `for v in I` definitely should iterate over the possibly infinite set of elements.  This is not implemented.

`for v in gens(I)` works.

**Comment by fieker** [comment]
On Fri, Sep 10, 2021 at 05:31:21AM -0700, wbhart wrote:
> What should that mean? Aren't there infinitely many elements? How would I order them? It doesn't seem like a useful operation.
> 
just syntactically 
 for i in some_mat_obj
has to iterate over all elements in the object. be it finite or
infinite, group or ring or ideal.

Would you support
  for v in VectorSpace()
to give you only a basis if the space is infinite and all elements
otherwise?

Its nt so much "useful", but predictable...

**Comment by wbhart** [comment]
Yeah you are right. I closed the issue.
