### ISSUE TITLE
`lift` returns wrong answers sometimes

### ISSUE THREAD

**Issue by tthsqe12** [oscar-system/Singular.jl#581]
With https://github.com/oscar-system/Singular.jl/pull/580, the documentation claims that the last two results should be equal. With `ordering = ordering_dp(2)` this is indeed the case, but not with this ordering. @hannes14 
```
julia> R, (x, y) = PolynomialRing(QQ, ["x", "y"], ordering = ordering_dp(1)*ordering_ds(1));

julia> M = Ideal(R, x^2, y*(y-1));

julia> SM = Ideal(R, y^2);

julia> (result, rest) = lift(M, SM)
(Singular Module over Singular Polynomial Ring (QQ),(x,y),(dp(1),ds(1),C), with Generators:
-y*gen(2), Singular Module over Singular Polynomial Ring (QQ),(x,y),(dp(1),ds(1),C), with Generators:
0)

julia> Matrix(SM)-Matrix(rest)
[y^2]

julia> Matrix(M)*Matrix(result)
[y^2 - y^3]
```

**Comment by tthsqe12** [comment]
Ok. So, how can we correctly document the behaviour of the two argument function lift(::sideal, ::sideal)?

**Comment by hannes14** [comment]
proposal:
@doc Markdown.doc"""
    lift(M::smodule, SM::smodule)

represents the generators of SM in terms of the generators of M.
Returns result, rest
If SM is in M, rest is the null module
otherwise: rest = SM
For global orderings: Matrix(SM)-Matrix(rest) = Matrix(M)*Matrix(result)
For non-global orderings: (Matrix(SM)-Matrix(rest) )*U= Matrix(M)*Matrix(result)
where U is some diagonal matrix of units
(to compute U, see  lift(M::smodule, SM::smodule, goodShape::Bool, isSB::Bool, divide::Bool))

**Comment by tthsqe12** [comment]
The existing documentation lift on modules has
```
    lift(M::smodule, SM::smodule, goodShape::Bool, isSB::Bool, divide::Bool)

Represents the generators of SM in terms of the generators of M.
Returns (result, rest) with
    Matrix(SM)*U - Matrix(rest) = Matrix(M)*Matrix(result)
...
```
So, whether the U is inside the parentheses or not needs clarification.

**Comment by hannes14** [comment]
Matrix(SM)*U - Matrix(rest) = Matrix(M)*Matrix(result) is the correct version,
additional: rest = reduce( SM, std( M))

**Comment by tthsqe12** [comment]
alright, I will add this to the docs.
